-- AGENDA : CONSTRAINT OR RULES

-- USED TO RESTRICT THE DATA/VALUES WHILE INSERTING THE DATA INTO A TABLE
--WHILE  CREATING TABLE ONLY WE INCLUDE CONSTRAINTS
--EX : WE WANT TO STOP THE DUPLICATES 
--UNIQUE -- WILL NOT ALLOW DUPLICATES INTO A COLUMN
--NOT NULL--WILL STOP ENTERING NULL VALUES

 CREATE TABLE S1 (EMP_ID VARCHAR(20) UNIQUE,EMP_NAME VARCHAR(20) NOT NULL,DOJ DATE ,SALARY NUMERIC(8,1))

INSERT INTO S1 VALUES ('A1102','TESLA','01-JAN-2025',9000)
INSERT INTO S1 VALUES('A1120','CARS','02-MAR-2026',8000)
SELECT*FROM S1

--CHECK -- IS USED TO ASS CONDITION BASED RULES ON A COL(<,>,>=,<=)
CREATE TABLE S2 
(EMP_ID    CHAR(29)      NOT NULL UNIQUE,
ENAME      VARCHAR(30)   NOT NULL,
DOJ         DATE         CHECK(DOJ >='01-JAN-2025'),
SAL         INT          CHECK (SAL >= 15000)
)

INSERT INTO S2 VALUES('A1101','PEERAN','01-MAR-2024',15100)
INSERT INTO S2 VALUES('A2201','BASHA','01-MAR-2026',16000)

--CREATE A TABLE WITH ANME AS CONS_01
--STU_ID --FIXED 6 CHARS -- NO DUPLICATES ,NO NULLS 
--STUD_NAME --VARIABALE UPTO 60 CHARS -- NO NULS
--STU_FEES   -- TOT NOF OF DIGITS (8,1) --FEES >15000
-- PROVIDE INSERT VIOLATING STU_FEES 

CREATE TABLE CONS_1 (STU_ID CHAR(9) NOT NULL UNIQUE,STU_NAME VARCHAR(20) UNIQUE, SALARY INT CHECK(SALARY >= 150000))
INSERT INTO CONS_1 VALUES('B1101','KOHLI',200000)
INSERT INTO CONS_1 VALUES('A1101','VIRAT',300000)
SELECT * FROM CONS_1

--PRIMARY KEY -- STOP NULL VALUES ,DUPLICATES
---DEFAULT -- IT TAKES THE DEFAULT VALUE WITHOUT NULL
CREATE TABLE S4 (EMP_ID CHAR(8) PRIMARY KEY,CITY VARCHAR(20) DEFAULT 'BANGLORE')
INSERT INTO S4(EMP_ID,CITY) VALUES ('A1','PUNE')
INSERT INTO S4(EMP_ID) VALUES ('A2')
 
SELECT*FROM S4
