--DDL Commands 
--DML COMMANDS
--CREATE ,ALTER,DROP,TRUNCATE
--CREATE -- COMMAND IS USED TO TO CREATE ANY DATA BASE 
--CREATE TABLE  TABLENAME
-- (COL1 DATATYPE,COL2 DATATYPE,COL3 DATATTYPE)

--WHAT IS A DATATYPE: TYPE OF INFORMATION OR tYPE OF DATA

CREATE TABLE STUDENTS
(STU_ID CHAR(6),STU_NAME VARCHAR(50), DOJ DATE ,LOC VARCHAR(20) ,FEES INT)

--CHAR DTYPE - FIXED NO OF CHARS EG; CHAR(5) [FIXED IN LENGTH]
--VARCHAR -- VARIABLE IN LENGTH OF CHAR EG: VARCHAR(20) [NO OF CHARS BE RANGED FROM 1 TO 1]
-- INT --NO DECIMALS ,NO LENGTH EG: INT
--DATE -- ONLY DATE VALUES ,NO LENGTH EG:DATE
--NUMERIC -- NUMBERS WITH FIXED DECIMALS EG:NUMERIC(6,1) -- [TOT NO OF DIGITS ARE 6 , NO OF FIXED DECIMALS ARE 1]
--                                          NIUMERIC(6,1) --123.4,1234.5
                                           -- NUMERIC (10,2) -- 
-- DECIMALS -- SIMILAR TO NUMERIC DATA TYPE 

SP_HELP STUDENTS  -- IT SHOWS THE DESCRIPTION OF TABLE

--ALTER COMMAND : IS USED TO ADD A NEW COLUMN IN EXISTING COLUMN
ALTER TABLE STUDENT ADD STU_MAIL VARCHAR(50)
ALTER TABLE STUDENTS DROP COLUMN DOJ

ALTER TABLE STUDENTS ADD   INT

ALTER TABLE STUDENTS ADD PINCODE  VARCHAR(60)
SP_HELP STUDENTS 

SP_RENAME 'STUDENTS.STU_ID','STU_IDD' --IT RENAMES THE COLUMN NAME 
SP_RENAME 'STUDENTS' ,'STUDENT' --IT RENAMES THE TABLE NAME 
SP_HELP STUDENT

--DROP : REMOVE ALL DATA &TABLE FROM DATABASE PERMANENTLY
DROP TABLE STUDENT


----------------------------------------------------------------------------------------------------------------
SP_HELP STUDENT 
--DML COMMANDS DATA MANIPULATION LANGUage
--INSERT ,UPDATE ,DELETE 

INSERT INTO STUDENT VALUES ('A1101','PEERAN','BANGLORE',20000,'RALLAPATIPEERAN')
SELECT * FROM STUDENT
INSERT INTO STUDENT (STU_IDD,STU_NAME) VALUES ('A11202','SIVA')
INSERT INTO STUDENT (STU_IDD ,FEES,STU_MAIL) VALUES ('A11202',30000,'SIVA23@GMAIL.COM')

--------------------
--UPDATE UPDATE OUR EXISTING RECORD VALUES 
SELECT * FROM STUDENT 
UPDATE STUDENT SET STU_NAME ='KASI' WHERE STU_IDD ='A11202'
UPDATE STUDENT SET STU_NAME ='VIRAT' ,FEES =24000 WHERE STU_NAME ='KASI'

--DELETE COMMAND - USED TO DELETE SPECIFIC RECORDS OR ALL THE DATA PRESENT IN THE TABLE
--THERE IS NO UNDO OPTION
DELET  E FROM STUDENTS