--Today We Are Going To Learn the 
--Multi Table Joins


--How To Import the Dataset -import.xls
--Drive Link https://drive.google.com/drive/folders/1BbB3TYUQp5N5eP30-CGO755XDLlKe1Fq
--Download The database.xls File 
--Here All The files Are There How To Import The Files 

--2STEPS REFRESH
--SELECT-DATABASE --CLICK ON RREFRESH
--SELECT ANYWHERE IJ QUERY WINDOW -- GO EDIT --INTELLIGENSE--REFRESH

--OPEN EXCEL FILE --ANALYZE WHAT ARE THEE TABLES THEY GIVEN ,WHAT ARE THE COMMON COLUMNS ARE PRESENT


SELECT A.CUSTOMERID, A.CUSTOMERNAME, A.CITY,
       B.ORDERID, B.ORDERDATE
FROM CUSTOMERS$ A
INNER JOIN ORDERS$ B
ON A.CUSTOMERID = B.CUSTOMERID;

SELECT BASE FROM INFORMATION_SCHEMA.TABLES
SELECT * FROM dbo.base;
 