select*from emp

--topic : Functions 
-- FUNCTIONS
-- USED TO MANIPULATE WITH DATA
-- DATE FUNCTIONS
-- CONTAIN LIST OF FUNCTIONS THAT CAN BE MANIPULATED/USED TO CALCULATES ON DATE COLUMNS

SELECT * FROM EMP
-- 1980-12-17
-- INTERVAL -- YEAR, MONTH, DAY, QUARTER, WEEKDAY, WEEKNUM
--fn is --DATEPART(interval,COLUMN NAME)
SELECT HIREDATE,
DATEPART(YEAR,HIREDATE) AS YR,
DATEPART(MONTH,HIREDATE) AS MN,
DATEPART(DAY,HIREDATE) AS DY,
DATEPART(QUARTER,HIREDATE)  AS QR,
DATEPART(WEEKDAY,HIREDATE) AS WK
FROM EMP


--REPLACE DATEPART FN WITH DATENAME
--SYNTAX OF 'DATENAME' -- DATENAME(INTERVAL,DATECOLUMN)
SELECT HIREDATE,
DATENAME(YEAR,HIREDATE) AS YR,
DATENAME(MONTH,HIREDATE) AS MN,
DATENAME(DAY,HIREDATE) AS DY,
DATENAME(QUARTER,HIREDATE)  AS QR,
DATENAME(WEEKDAY,HIREDATE) AS WK
FROM EMP

--DATEADD : IS A FUNCTION WHICH IS USED TO ADD A SPECIFIC NUMBER OF INTERVALS TO THE COLUMN

SELECT HIREDATE,
DATEADD(MONTH,1,HIREDATE) ,
DATEADD(YEAR,1,HIREDATE) FROM EMP        -- HERE U CAN OBSERVE THAT EVERY COLUMN AND YEAR ADDED 1 YEAR EXTRA FROM CURRENT 

--DATEDIFF : IS A FUNCTION USED TO CALCULATE THE DIFFERENCE BETWEEN TWO DATES 

SELECT [ORDER_DATE],[SHIP_DATE],
DATEDIFF(DAY,[ORDER_DATE],[SHIP_DATE]) AS DAYS_DIFF
FROM SALES_DATA

SELECT HIREDATE,
DATEDIFF(YEAR,HIREDATE,GETDATE()) AS YEARS_DIFF ,             --GETDATE() IS A FUNCTION IT GETS CURRENT SYSTEM DATE TIME
DATEDIFF(MONTH,HIREDATE,GETDATE()) AS MONTHS_DIFF 
FROM EMP

SELECT GETDATE()

--EOMONTH
SELECT HIREDATE ,EOMONTH(HIREDATE,2) FROM EMP

-- 1980-12-17 -- ADD 2 MONTHS -- 1981-02-17 -- ROEUND OFF TO LAST DATE -- 1981-02-28

SWITCHOFFSET
--
-- USED TO CONVERT 1 DATETIME ZONE INTO ANOTHER DATETIME ZONE
SELECT SYSDATETIMEOFFSET()
-- 2025-04-28 22:17:46.0490054 +05:30

SELECT SWITCHOFFSET('2026-05-01 11:56:38.8076280 +05:30', '-10:00')

----Next Cocnept 
-- LEN(COLUMN_NAME)                            -- RETURNS NO OF CHARS INCLUDE ANY SPECIAL CHARS ALSO [SPACE, COMMA, COLON, ... ]
-- LEFT(COLUMN_NAME, NO OF CHARS)              ---- RETURNS SPECIFIED NO OF CHARS FROM STARTING ONWARDS IN EACH CUSTOMER NAME
-- RIGHT(COLUMN_NAME, NO OF CHARS)             ----- RETURNS SPECIFIED NO OF CHARS FROM ENDING ONWARDS IN EACH CUSTOMER NAME
-- SUBSTRING(COL_NAME, START POS, NO OF CHARS) -- RETURNS SPECIFIED NO OF CHARS FROM SPCIFIED POS

select *from emp
select job,
len(job) as leght_,
LEFT(job,3) as lef_char,
RIGHT(job,3) as right_char,
SUBSTRING(job,2,4) as sub_string
from emp

--Ex:-- CA-2016-152156 - CA, 2016, 152156

--CONCAT-Function
select [ENAME],[JOB],
concat([ENAME],[JOB])as con1 from emp

--CHAIRINDEX - is is used to search a character or word in every column value and returns the Pos of CHAR/Word
select ename,CHARINDEX('E',ename) as search from emp  --it returns the position
select hiredate,CHARINDEX('1980',hiredate) as search2 from emp

--TRIM
select TRIM(ename) as cust_name,UPPER(ename) as cust_upper from EMP

--CASE,IIF Statements
--IIF(condition,True_value,False_value)
--IIF(2>3,A,B)

select price,
IIF(price>40000,'High','Low') as Price_values from Products

--profit>0 Pos_profit,0-Zero,0<-Neg Profit
select profit,
IIF(profit>0 ,'Pos profit',iif(profit=0,'Zero','Neg profit')) as profit_categories 
from sales
order by profit_categories desc

-- CASE WHEN COND1 THEN VALUE1 WHEN COND2 THEN VALUE2 .... ELSE VALUEN END
select profit,
(CASE when profit>= 4200 then 'high profit' else 'Low Profit') as Profit_cat )
from sales_data
order by Profit DESC

--MathFunctions
select profit ,
Round(profit,1) as roundedd,
CEILING(profit) AS CEIL,
FLOOR (profit) AS FLR
FROM SALES_DATA


