select*from emp

--topic : Functions 
-- FUNCTIONS
-- USED TO MANIPULATE WITH DATA
-- DATE FUNCTIONS
-- CONTAIN LIST OF FUNCTIONS THAT CAN BE MANIPULATED/USED TO CALCULATES ON DATE COLUMNS

SELECT * FROM EMP
-- 1980-12-17
-- INTERVAL -- YEAR, MONTH, DAY, QUARTER, WEEKDAY, WEEKNUM
--fn is --DATEPART(interval,COLUMN NAME)
SELECT HIREDATE,
DATEPART(YEAR,HIREDATE) AS YR,
DATEPART(MONTH,HIREDATE) AS MN,
DATEPART(DAY,HIREDATE) AS DY,
DATEPART(QUARTER,HIREDATE)  AS QR,
DATEPART(WEEKDAY,HIREDATE) AS WK
FROM EMP


--REPLACE DATEPART FN WITH DATENAME
--SYNTAX OF 'DATENAME' -- DATENAME(INTERVAL,DATECOLUMN)
SELECT HIREDATE,
DATENAME(YEAR,HIREDATE) AS YR,
DATENAME(MONTH,HIREDATE) AS MN,
DATENAME(DAY,HIREDATE) AS DY,
DATENAME(QUARTER,HIREDATE)  AS QR,
DATENAME(WEEKDAY,HIREDATE) AS WK
FROM EMP

--DATEADD : IS A FUNCTION WHICH IS USED TO ADD A SPECIFIC NUMBER OF INTERVALS TO THE COLUMN

SELECT HIREDATE,
DATEADD(MONTH,1,HIREDATE) ,
DATEADD(YEAR,1,HIREDATE) FROM EMP        -- HERE U CAN OBSERVE THAT EVERY COLUMN AND YEAR ADDED 1 YEAR EXTRA FROM CURRENT 

--DATEDIFF : IS A FUNCTION USED TO CALCULATE THE DIFFERENCE BETWEEN TWO DATES 

SELECT [ORDER_DATE],[SHIP_DATE],
DATEDIFF(DAY,[ORDER_DATE],[SHIP_DATE]) AS DAYS_DIFF
FROM SALES_DATA

SELECT HIREDATE,
DATEDIFF(YEAR,HIREDATE,GETDATE()) AS YEARS_DIFF ,             --GETDATE() IS A FUNCTION IT GETS CURRENT SYSTEM DATE TIME
DATEDIFF(MONTH,HIREDATE,GETDATE()) AS MONTHS_DIFF 
FROM EMP

SELECT GETDATE()

--EOMONTH
SELECT HIREDATE ,EOMONTH(HIREDATE,2) FROM EMP

-- 1980-12-17 -- ADD 2 MONTHS -- 1981-02-17 -- ROEUND OFF TO LAST DATE -- 1981-02-28

SWITCHOFFSET
--
-- USED TO CONVERT 1 DATETIME ZONE INTO ANOTHER DATETIME ZONE
SELECT SYSDATETIMEOFFSET()
-- 2025-04-28 22:17:46.0490054 +05:30

SELECT SWITCHOFFSET('2026-05-01 11:56:38.8076280 +05:30', '-10:00')


